[build]
    functions = "functions"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200
[[redirects]]
  from = "/authenticate"
  to = "/index.html"
  status = 200

[template.environment]
  REACT_APP_STYTCH_PUBLIC_TOKEN = "STYTCH_PUBLIC_TOKEN"
  STYTCH_PROJECT_ID = "STYTCH_PROJECT_ID"
  STYTCH_PROJECT_SECRET = "STYTCH_SECRET"
